version: '2'

services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./work-report-management:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  php:
    build: ./php
    container_name: "laravel-php"
    volumes:
      - ./work-report-management:/src

  mysql:
    image: mysql
    container_name: "laravel-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: sharerepo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306
